import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import TaskBar from "@/components/TaskBar/TaskBar";


export const metadata: Metadata = {
  title: "Windows 11 Portfolio",
  description: "Generated by Iliaw",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={` h-full antialiased`}
    >
      <body className="min-h-full flex flex-col ">
        {children}
        <TaskBar/>
        </body>
      
    </html>
  );
}
